Create new test vectors
cfrg/draft-irtf-cfrg-voprf pull request #158
Opened 2020-10-12 22:43 UTC by claucece

2020-10-13 11:25 UTC, claucece commented
cc. @chris-wood and @armfazh .

2020-10-15 19:19 UTC, armfazh requested changes

2020-10-15 19:19 UTC, armfazh commented on poc/oprf.sage
> +    Ciphersuite("OPRF-P384-HKDF-SHA512-SSWU-RO", ciphersuite_p384_hkdf_sha512_sswu_ro, GroupP384(), "RFCXXXX-P384_XMD:SHA-512_SSWU_RO_", hashlib.sha512),
Test vectors change between runs. It is expected that this script returns the same vectors everytime we run it.

2020-10-16 00:23 UTC, claucece commented on poc/oprf.sage
> +    Ciphersuite("OPRF-P384-HKDF-SHA512-SSWU-RO", ciphersuite_p384_hkdf_sha512_sswu_ro, GroupP384(), "RFCXXXX-P384_XMD:SHA-512_SSWU_RO_", hashlib.sha512),
Yeah.. it was like that since the beginning of the POC.. and I didn't know if that is what was wanted (as it was there). I can create a 'random scalar generation' function that always return the same valid scalar for creating same test vectors. 
cc. @chris-wood

2020-10-16 00:24 UTC, claucece commented on draft-irtf-cfrg-voprf.md
>    - HashToGroup(): P256_XMD:SHA-256_SSWU_RO_
Interesting. Personally, I think it will be better if we use SHA-256, as the size is smaller. But maybe this was targeted for an specific security level that SHA512 gives. Let's discuss tomorrow.

2020-10-16 00:29 UTC, claucece commented on poc/vectors/allVectors.json
>      "suite": "OPRF-P256-HKDF-SHA512-SSWU-RO",
Oh, yes. Names get repeated. I'll change.

2020-10-16 13:42 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
>    - HashToGroup(): P256_XMD:SHA-256_SSWU_RO_
We should go with SHA256!

2020-10-16 13:42 UTC, chris-wood commented on poc/oprf.sage
> +    Ciphersuite("OPRF-P256-HKDF-SHA512-SSWU-RO", ciphersuite_p256_hkdf_sha512_sswu_ro, GroupP256(), "RFCXXXX-P256_XMD:SHA-512_SSWU_RO_", hashlib.sha512),
Yeah, good catch. We're not using HKDF anymore.

2020-10-16 13:42 UTC, chris-wood commented on poc/oprf.sage
> +    Ciphersuite("OPRF-P384-HKDF-SHA512-SSWU-RO", ciphersuite_p384_hkdf_sha512_sswu_ro, GroupP384(), "RFCXXXX-P384_XMD:SHA-512_SSWU_RO_", hashlib.sha512),
We can make them deterministic, but let's do that in a separate change.

2020-10-16 13:42 UTC, chris-wood commented on poc/test_oprf.sage
> +        vector["suite dst"] = client.suite.dst
```suggestion
        vector["dst"] = client.suite.dst
```

2020-10-16 18:08 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +    "RFCXXXX-P256_XMD:SHA-512_SSWU_RO_"
Got it ;)

2020-10-18 19:18 UTC, claucece commented on draft-irtf-cfrg-voprf.md
>    - HashToGroup(): P256_XMD:SHA-256_SSWU_RO_
Ok ;)

2020-10-18 19:21 UTC, claucece commented on poc/oprf.sage
> +    Ciphersuite("OPRF-P256-HKDF-SHA512-SSWU-RO", ciphersuite_p256_hkdf_sha512_sswu_ro, GroupP256(), "RFCXXXX-P256_XMD:SHA-512_SSWU_RO_", hashlib.sha512),
Changed ;)

2020-10-18 19:23 UTC, claucece commented on poc/oprf.sage
> +    Ciphersuite("OPRF-P384-HKDF-SHA512-SSWU-RO", ciphersuite_p384_hkdf_sha512_sswu_ro, GroupP384(), "RFCXXXX-P384_XMD:SHA-512_SSWU_RO_", hashlib.sha512),
I'll do that in another PR.

2020-10-18 20:59 UTC, claucece commented on draft-irtf-cfrg-voprf.md
>      SHA-512.
I'll open an issue for tracking this.

2020-10-18 20:59 UTC, claucece commented
@armfazh @chris-wood please, take a look at this.

2020-10-19 13:59 UTC, chris-wood requested changes

2020-10-19 13:59 UTC, chris-wood commented on poc/oprf.sage
> +voprf_ciphersuites = {
Why are these separate? The only difference between VOPRF and OPRF the mode, right?

2020-10-19 13:59 UTC, chris-wood commented on poc/oprf.sage
> +voprf_ciphersuites = {
(I recommend deleting them)

2020-10-19 13:59 UTC, chris-wood commented on poc/test_oprf.sage
> +                "Point": to_hex(group.serialize(P)),
Why is "Point" needed?

2020-10-19 13:59 UTC, chris-wood commented on poc/test_oprf.sage
> +        vectors["Verifiable: " + suite.name] = protocol.run(client, server, "test information")
I'd revert this change.

2020-10-19 15:31 UTC, claucece commented on poc/test_oprf.sage
> +        vectors["Verifiable: " + suite.name] = protocol.run(client, server, "test information")
OK.

2020-10-19 15:33 UTC, claucece commented on poc/oprf.sage
> +voprf_ciphersuites = {
Yes.. it was manly to address a comment by @armfazh that the names of the ciphersuites do not reflect the mode, as, in the past, it was only: `OPRF-P256-SHA256-SSWU-RO`. I'll delete them.

2020-10-19 15:33 UTC, claucece commented on poc/test_oprf.sage
> +                "Point": to_hex(group.serialize(P)),
Not really needed. It was for debugging.

2020-10-19 16:25 UTC, chris-wood approved these changes

2020-10-19 16:26 UTC, merged