Address issues in the draft
cfrg/draft-irtf-cfrg-voprf pull request #169
Opened 2020-10-20 14:30 UTC by claucece

2020-10-22 21:26 UTC, chris-wood requested changes

2020-10-22 21:26 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  - Elliptic curve name: ristretto255 {{RISTRETTO}}
```suggestion
  - Name: ristretto255 {{RISTRETTO}}
```

2020-10-22 21:26 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  - HashToGroup(): ristretto255_XMD:SHA-256_ELL2_RO\_
Can we reference the relevant hash-to-curve section in the document?

2020-10-22 21:26 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  - Serialization: The 32-byte little-endian encoding of a group element
Can we simply reference the [`Encode`](https://tools.ietf.org/html/draft-irtf-cfrg-ristretto255-decaf448-00#section-4.3.2) and `Decode` APIs? We shouldn't specify anything else, I think.

2020-10-22 21:26 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +abstraction level.
```suggestion
```

2020-10-22 21:26 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +abstraction level.
```suggestion
```

2020-10-22 21:26 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  - Serialization: The 32-byte little-endian encoding of a group element
(DItto for decaf448)

2020-10-22 21:26 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  - HashToGroup(): ristretto255_XMD:SHA-256_ELL2_RO\_
Those sections are [here for ristretto255](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-10#appendix-B) and [here for decaf448](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-10#appendix-C)

2020-10-22 22:27 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +  - Elliptic curve name: ristretto255 {{RISTRETTO}}
ok ;)

2020-10-22 22:30 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +  - Serialization: The 32-byte little-endian encoding of a group element
For elements (or points), yes, there is no need of anything but the encode and decode. But for scalars, these are not the functions specified for them. That is why I added a serialization of them in accordance with the Ristretto draft.

2020-10-22 22:30 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +abstraction level.
Ok.

2020-10-22 22:30 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +abstraction level.
Ok.

2020-10-23 01:32 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +  - Serialization: The 32-byte little-endian encoding of a group element
Serialization of scalars is mostly universal, since they are positive numbers less than group order. Then implementor can just call I2OSP

2020-10-23 17:10 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +  - Serialization: The 32-byte little-endian encoding of a group element
Removed now.

2020-10-23 18:53 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +  - HashToGroup(): ristretto255_XMD:SHA-256_ELL2_RO\_
Done :)

2020-10-23 18:53 UTC, claucece commented
@armfazh @chris-wood please, review until here prior to me changing the poc vectors.

2020-10-23 18:53 UTC, armfazh reviewed
Some comments

2020-10-23 18:53 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +- Order(): Outputs the order of the group (i.e. order of `p`).
```suggestion
- Order(): Outputs the order of GG (i.e. `p`).
```

2020-10-23 18:53 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +  subgroupi (the output of `Order()`).
```suggestion
  defined in {{I-D.irtf-cfrg-hash-to-curve}} setting the target field to GF(p).
```

2020-10-23 18:53 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +def SetupBaseServer(suite, skS):
In the spec, the Setup functions are called once, so they are in charge to generate keys. 
Otherwise, you also need to specify how those keys were generated.

2020-10-23 18:53 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +group's fixed generator. Note that to set up a context, a pre-existing key pair
revert this

2020-10-23 18:53 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +    it as a group element by using the 'Decode' function from {{!RISTRETTO}}.
```suggestion
  - Deserialization: Converts a valid 32-byte string to 
    a group element by using the 'Decode' function from {{!RISTRETTO}}.
```

2020-10-23 18:53 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +    using the 'Encode' function from {{!RISTRETTO}}.
```suggestion
  - Serialization: Converts a group element to a 32-byte string 
    using the 'Encode' function from {{!RISTRETTO}}.
```

2020-10-23 18:53 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +    "VOPRF05-edwards25519_XMD:SHA-256_ELL2_RO\_"
Following Appendix B of hash to curve draft.
it might be:  VOPRF05-ristretto25519\_XMD:SHA-256\_RS255MAP\_RO\_

2020-10-23 18:53 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +    "VOPRF05-edwards448_XMD:SHA-512_ELL2_RO\_"
likewise `VOPRF05-decaf448_XMD:SHA-512_D448MAP_RO_`

2020-10-23 18:59 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +    Using Ristretto encoding, it looks like:
Ok.

2020-10-23 19:00 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +- Order(): Outputs the order of the group (i.e. order of `p`).
Ok.

2020-10-23 19:01 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +  subgroupi (the output of `Order()`).
Ok.

2020-10-23 19:02 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +def SetupBaseServer(suite, skS):
Mmm.. this was trying to solve: https://github.com/cfrg/draft-irtf-cfrg-voprf/issues/168.. what do you suggest instead?

2020-10-23 19:03 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +    it as a group element by using the 'Decode' function from {{!RISTRETTO}}.
Ok.

2020-10-23 19:04 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +    using the 'Encode' function from {{!RISTRETTO}}.
Ok.

2020-10-23 19:04 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +    "VOPRF05-edwards25519_XMD:SHA-256_ELL2_RO\_"
Solved.

2020-10-23 19:04 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +    "VOPRF05-edwards448_XMD:SHA-512_ELL2_RO\_"
Solved.

2020-10-23 19:09 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +      `15112221349535400772501151409588531511454012693041857206046113283949847762202`
Solved.

2020-10-23 19:21 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +group's fixed generator. Note that to set up a context, a pre-existing key pair
No, please don't revert this. We need to allow context setup using external keys. This is needed for OPAQUE.

2020-10-23 19:21 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +def SetupBaseServer(suite, skS):
This is fine as-is. Please keep it.

2020-10-23 19:22 UTC, chris-wood approved these changes

2020-10-23 19:23 UTC, chris-wood commented
@claucece is this now ready for a full review, or is it still WIP?

2020-10-23 19:31 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  if !skS: (skS, _) = KeyGen(GG)
Let's remove this line, and assert that `skS` is valid in the text. We can then say that `KeyGen` is used to generate `skS` (and `pkS` for the verifiable mode) and passed to `SetupBaseServer` when needed.

2020-10-23 22:11 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +    directly corresponds with scalar multiplication in the edwards group.
```suggestion
    directly corresponds with scalar multiplication in the Edwards curve.
```

2020-10-23 22:12 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +    directly corresponds with scalar multiplication in the edwards group.
```suggestion
    directly corresponds with scalar multiplication in the Edwards curve.
```

2020-10-23 22:12 UTC, armfazh approved these changes

2020-10-26 10:53 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +  if !skS: (skS, _) = KeyGen(GG)
Ok ;)

2020-10-26 10:55 UTC, claucece commented
@chris-wood this should close: #168 #163 #155 #154 #152 #151 #142.. I'm still missing to solve #165.. can you maybe take a look at the issue?

2020-10-26 11:00 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +    directly corresponds with scalar multiplication in the edwards group.
Done

2020-10-26 11:00 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +    directly corresponds with scalar multiplication in the edwards group.
Done.

2020-10-26 11:14 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +  if !skS: (skS, _) = KeyGen(GG)
I think is solved now ;)

2020-10-26 11:15 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +def SetupBaseServer(suite, skS):
Ok ;)

2020-10-26 15:44 UTC, claucece commented
@chris-wood @armfazh it is ready now.

2020-10-26 17:29 UTC, armfazh approved these changes

2020-10-26 17:44 UTC, chris-wood requested changes
Nearly there!

2020-10-26 17:44 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +to calling the setups function.
This is redundant with the sentence above, I think. 

```suggestion
```

2020-10-26 17:44 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +configuring a verifiable client context.)
```suggestion
```

2020-10-26 17:44 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +Note that `VerifyFinalize` is not used in the main OPRF protocol. It is
Isn't it also true that `FullEvaluate` is not used in the main OPRF protocol? If so, can we note that?

2020-10-26 17:44 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +exposed as an API for applications that might need it.
```suggestion
`FullEvaluate` and takes ClientInput values, and it is useful for applications
that need to compute the whole OPRF protocol on the server side only.
```

2020-10-26 17:44 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
>  exposed as an API for building higher-level protocols.
```suggestion
exposed as an API for building higher-level protocols.

Note that `FullEvaluate` and `VerifyFinalize` are not used in 
the main OPRF protocol.
```

2020-10-26 17:44 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +output. This functionality allows applications batch inputs together to
```suggestion
output. This functionality lets applications batch inputs together to
```

2020-10-26 17:44 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +      `0x6666666666666666666666666666666666666666666666666666666666666658`
Is the generator useful information for ristretto255? (I don't think users need it to implement the OPRF, right?)

2020-10-26 17:44 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +    directly corresponds with scalar multiplication in the Edwards group.
```suggestion
  - Scalar multiplication: Scalar multiplication according to {{!RISTRETTO}}.
```

2020-10-26 17:44 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +    - x = `0x4F1970C66BED0DED221D15A622BF36DA9E146570470F1767EA6DE324A3D3A46412AE1AF72AB66511433B80E18B00938E2626A82BC70CC05E`
Ditto here for the decaf448 generator.

2020-10-26 17:44 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +    directly corresponds with scalar multiplication in the Edwards group.
```suggestion
  - Scalar multiplication: Scalar multiplication according to {{!RISTRETTO}}.
```

2020-10-26 17:47 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +to calling the setups function.
Ok.

2020-10-26 17:49 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +Note that `VerifyFinalize` is not used in the main OPRF protocol. It is
Yes!

2020-10-26 17:55 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +      `0x6666666666666666666666666666666666666666666666666666666666666658`
They do. You do:

```
  G = GG.Generator()
```

for `GenerateProof()`.

2020-10-26 17:56 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +    directly corresponds with scalar multiplication in the Edwards group.
Done.

2020-10-26 17:57 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +    directly corresponds with scalar multiplication in the Edwards group.
Done.

2020-10-26 17:58 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +configuring a verifiable client context.)
Ok.

2020-10-26 18:52 UTC, chris-wood approved these changes

2020-10-26 19:03 UTC, merged