Change dst of hashToGroup #165
cfrg/draft-irtf-cfrg-voprf pull request #170
Opened 2020-10-27 14:44 UTC by claucece

2020-10-27 14:45 UTC, claucece commented
cc. @chris-wood @armfazh

2020-10-28 01:20 UTC, chris-wood requested changes

2020-10-28 01:20 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +    "VOPRF05" || self.contextString
`self.contextString` is a little hard to parse here (out of context), so how about:

```suggestion
    "VOPRF05" || contextString, where `contextString` is that which is computed in the Setup functions.
```

(or something like that)

2020-10-28 11:23 UTC, claucece commented on draft-irtf-cfrg-voprf.md
> +    "VOPRF05" || self.contextString
Changed.

2020-10-28 12:32 UTC, chris-wood approved these changes

2020-10-28 12:32 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +    "VOPRF05" || contextString, , where `contextString` is that which is
```suggestion
    "VOPRF05" || contextString, where `contextString` is that which is
```

2020-10-28 12:32 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +    "VOPRF05" || contextString, , where `contextString` is that which is
```suggestion
    "VOPRF05" || contextString, where `contextString` is that which is
```

2020-10-28 12:32 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +    "VOPRF05" || contextString, , where `contextString` is that which is
```suggestion
    "VOPRF05" || contextString, where `contextString` is that which is
```

2020-10-28 12:32 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +    "VOPRF05" || contextString, , where `contextString` is that which is
```suggestion
    "VOPRF05" || contextString, where `contextString` is that which is
```

2020-10-28 12:32 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +    "VOPRF05" || contextString, , where `contextString` is that which is
```suggestion
    "VOPRF05" || contextString, where `contextString` is that which is
```

2020-10-28 12:33 UTC, merged