Change tests vectors
cfrg/draft-irtf-cfrg-voprf pull request #185
Opened 2020-11-04 14:36 UTC by claucece

2020-11-04 14:44 UTC, claucece commented
cc./ @chris-wood

2020-11-04 16:30 UTC, chris-wood commented on poc/test_oprf.sage
> +        vector["skS"] = "{:02x}".format(server.skS)
Why doesn't `to_hex` work here?

2020-11-04 16:30 UTC, chris-wood commented on poc/test_oprf.sage
> +                "Token": "{:02x}".format(r),
Same here.

2020-11-04 16:31 UTC, chris-wood requested changes
LGTM modulo one nit :)

2020-11-04 16:37 UTC, armfazh commented
Two things,
as I mentioned in the other repo, I prefer to mantain the 0x prefix for test vectors in sage.

second, as you can see test vectors are not running deterministically since the change not only the 0x prefix.

2020-11-04 17:07 UTC, chris-wood commented
> as I mentioned in the other repo, I prefer to mantain the 0x prefix for test vectors in sage.

Go can't parse them as-is, so let's drop the prefix.

> second, as you can see test vectors are not running deterministically since the change not only the 0x prefix.

Run the following:

```
$ make vectors
$ cp vectors/allVectors.json vectors.json
$ make vectors
$ diff vectors/allVectors.json vectors.json
```

And you'll see no output change.

2020-11-04 17:24 UTC, armfazh commented
> Go can't parse them as-is, so let's drop the prefix.

```
  s := "0x6432"
  fmt.Println( hex.DecodeString(s[2:]))
```

> And you'll see no output change.

I may be running things the wrong way, but why vectors change in this PR?

2020-11-04 17:30 UTC, chris-wood commented
I'll let @claucece comment on the hex formatting. If Go can parse them, then why are we making this change? :)

2020-11-04 22:58 UTC, claucece commented on poc/test_oprf.sage
> +        vector["skS"] = "{:02x}".format(server.skS)
Because server.skS is an int: 

``class 'sage.rings.integer.Integer'>`, which is not accepted by `to_hex` as it checks: `assert isinstance(octet_string, (bytes, bytearray))`. That is the reason why, as it can be seen in the code, it was previously using `hex`.

But it can be added to `to_hex`, if that is what is wanted.

2020-11-04 23:01 UTC, claucece commented
@armfazh @chris-wood , for me the test vectors do change all the time:

```
~/repos/projects/mine-oprf/poc (master ✔) ᐅ make vectors
Parsing test_oprf.sage
Removing vectors folder, if present
Creating vectors folder
sage test_oprf.sage
Testing with test Vectors on Ed25519Point
Testing with test Vectors on Ed448GoldilocksPoint
Testing one way map on Ed25519Point
Testing one way map on Ed448GoldilocksPoint

~/repos/projects/mine-oprf/poc (master ✘)✹ ᐅ cp vectors/allVectors.json vectors.json

~/repos/projects/mine-oprf/poc (master ✘)✹✭ ᐅ make vectors
Removing vectors folder, if present
Creating vectors folder
sage test_oprf.sage
Testing with test Vectors on Ed25519Point
Testing with test Vectors on Ed448GoldilocksPoint
Testing one way map on Ed25519Point
Testing one way map on Ed448GoldilocksPoint
~/repos/projects/mine-oprf/poc (master ✘)✹✭ ᐅ diff vectors/allVectors.json vectors.json
4c4
<     "skS": "6174f54bbdafdd3bcfd4a06041237b0dba55be738921ac19f934c9916d2e3c53",
---
>     "skS": "3f3d86c3e0e019c1c5e47d3b1743cf3b333d8459e92f1fa45c1a19c8421ac689",
9,10c9,10
<           "BlindedElement": "037f8f555d4f6a2c3b21f6a353a52f01bea3b5a2b8436ec2c01a01cf67eee96517",
<           "Token": "46736c42376170a98651af33ac718e4c44f8220586a8e4ee92157925c3aef53a"
---
>           "BlindedElement": "02e53afa2302fad27acf2d56bbea38074dbbbc23fb7363c43496769e579d5220d7",
>           "Token": "83bcf6b5fa1b088c15dc297ae2353f198dac2e3e2fefd7ef7a5f3a9396560271"
12c12
<         "ClientOutput": "879c5725eef4f560969043f3cf932720f386ab54f9a135106d23e81c30884fcd",
---
>         "ClientOutput": "656284f1224bf7216757ffc81859aeb334344777b89d1e9ee02a955d7152f146",
14c14
<           "EvaluatedElement": "039ee453ad56d5fd62228c9b903b9818ba8f096af8edada5256e19a598f1d4190b"
---
>           "EvaluatedElement": "02239be9838d4ab2d5b7eb03cad5c612f5362f3a1fedeb46660b88d46791811f34"
20c20
<           "IssuedToken": "02af20a9f92e8bdbca7b2b7b450043a8e349f7ff58327157301814bf0f3585f77c"
---
>           "IssuedToken": "022c6578d014c3b68ffd5e6138c2b6d352593d4175328b019b8350f6019f375c61"
25,26c25,26
<           "BlindedElement": "0328a3f25f1cd537e3410f709a014b91744284a610aec49010e424b18190338447",
<           "Token": "ed8bc3e0f19f3828ac0dda46ffefed869b3573a28845a1cdc8156dda1cb42c82"
---
>           "BlindedElement": "03e55aa5f117628888914e252f2eb8c40069b8634532cc7c9c1fb0e8f27353890f",
>           "Token": "17538a0fbdafe78930da224d276e7d03c38c59e8f4c6d683e352d59ad8f1d0e6"
28c28
<         "ClientOutput": "0a717871858c02c190dc47fe7fa233a66fc65c43b0a4b2114a891f1ac1d13465",
---
>         "ClientOutput": "bef6f03c6d4e839171c2038ff206efdf9175a1b71702afde959989c1c7316669",
30c30
<           "EvaluatedElement": "0242331d23898daf954efc95972ee966e4f9d50f6ecb21dfd854dc5b39558805c1"
---
>           "EvaluatedElement": "039cf32aa7c47d37b39dec187baeedf64ecb288a44641fdc55b6bbba99bd8c3605"
36c36
<           "IssuedToken": "034cd19cf5644905d8262c548f63c1277498e003c0a543076687ca76764f35ebf7"
---
>           "IssuedToken": "02e65e3c2f9cbc94d12fbddd1fa848199318890cd6d7604ae5a9c2bfbe24848395"
41,42c41,42
<           "BlindedElement": "024b37f532b61b952a3c1475ce3fe27df2ef9916287036d52987d8e4de17baff9b",
<           "Token": "a24e01948190264065c6060ee1ed79677099ee55b43d6b3d9473f5183433b3eb"
---
>           "BlindedElement": "02e11a9284e7181ad29031868dfc84fc2d228283538e57d3257e84d012705adb29",
>           "Token": "59518b657d3f019ddf427d1950cbf23edd454f187bbd19256cf2d550fd06ae74"
44c44
<         "ClientOutput": "0f2f9d00bf266a1b9edda5968c6636f3fb450b73ec74a102d79f34ab345ffc79",
---
>         "ClientOutput": "b9507a0d95e82bfa96b85fd18e5297ba0b690aef4d139a3f20793d0f84dcd0bb",
46c46
<           "EvaluatedElement": "03e23a4a316185015eb275ab0120b712359ee9a0af771d9912cc8279e89ae41e45"
---
>           "EvaluatedElement": "02cc74d13f8d75d25e3e7862eecf144b9eeae9776c02e1b7cbfefc5264b7714bed"
52c52
<           "IssuedToken": "035ad651c35210bc756028cb55dc53af49617fe96691b6aef5a1067ca0e86a1075"
---
>           "IssuedToken": "03b31879fc43c0182370d231535d2665001534259f04d3f254e039fe31adf6b06f"
59c59
<     "skS": "2c5ca1fb743a013921efc828bcea630c81fb4ca9b4ed2e09e10462af8cb5b7dbed8c74aa895813ec9605646aa81c7f7",
---
>     "skS": "bbbb68e65c633c6711c1c75c215f7276f527714e9150ceeac5f8fcf0720308d07cdac06b8ed12948946f1eba55b2349b",
64,65c64,65
<           "BlindedElement": "023b6f6c633ab3e0e8445a458e031c60be181ca7085a3df52521692292e1cacfcef85a8291a980d3ad37d0953b7abc1b5c",
<           "Token": "579f77ec5404344e35fc5f0d5fa1d5c3402f39795135b314b9a56c2dbcfa8db48c88e11a9b70ab7226e92d354d0a0d08"
---
>           "BlindedElement": "034767a26aafb0de6ca31d1d29fd26dc3880893dd2122fbd84d16292d99955f8580ecddcd1347bcb0f8cfa64620b884bf2",
>           "Token": "bfaba18e6da8cc89f57dcfa306363716edf0d84fa4ffd1ad521e1982d0c95e3640d0c9b6d03ec2b88a359bd81a60509c"
67c67
<         "ClientOutput": "d869372ea764097af2ef2340deb47952dbed81a63ce837d9c041bb791160720ad25aa55dd08c93f574d32d1c11a89e3d4f0d7698fcefb70eef6c5da983364356",
---
>         "ClientOutput": "16e4511da9d3676eaa87ff7c7ee8a3b3c6d02f9eff3f2839fcdfacfeaa52d3dc53c6ef81b4c7479061f7b213c3e14d1728c6cddfa874fb4234cdb927173e49c3",
69c69
<           "EvaluatedElement": "02e4883484118fdd15e080a280d1b66cd2733dbc9bf81d8d96affa3975ee02a74c903547add3b240b1bad34d2bb234502f"
---
>           "EvaluatedElement": "02903c0efd55a302aae1b78bd7fd86a4fe505ac82e6c6a49ea895314aafe5534680c7d1595f2602d2d7a1bab55494851ce"
75c75
<           "IssuedToken": "02f849a885c0953f9f7e08a58f59f0e1e0ec48842aaf0744f9e756459dddba929bd74bb9f68223236a3f2eb3340504cc5d"
---
>           "IssuedToken": "024c96c8afcd4fd80c1b3b3c630435e0bc7dd7ddc9e9d72c85c26580487d78759d055d046de8d1ce8aca484a5036388310"
80,81c80,81
<           "BlindedElement": "0290d8c766bfdc4cc3b116cb6055c8021a9ac054484db952749701b1dbf8b683f3410382908852a0757d77c87b406a4ffd",
<           "Token": "ad4f8d61d3eb4357b2a483be55992e2ee92317a26274bde189712cce3955d9f6329eea5c98a24d7ee5b56a88a373455f"
---
>           "BlindedElement": "02182ddf4f4ab91fa8e075ba047af978243a15b1b06d3c3ca0c7abb5b6cdd9db0643e64624772db804cb22b3504141b5c6",
>           "Token": "d51f11c35a47716c1b629a77b16d934b631f0582cea43441a161b28e01e4e165958be2a15be54ac701d4f3be1d776858"
83c83
<         "ClientOutput": "c57befcbb9deb2635d81557ea4c012ca5402dc2399bc51c8526999785d88968326f80b919cc074e401b5f2568b4a4d5bdabbc3e73457855183434f046c5ef065",
---
>         "ClientOutput": "6e4066baa388bc7e44c5f1c17ab80069cd79036d6162cc40e7bf40a13ab1f547c8416d7b2cbf2e266171c25c04fa16a48610f8f93e203b4ac0ba0c44d4bbbdd1",
85c85
<           "EvaluatedElement": "0256f199d65eb1945b1d436847eaa9e02a8366f94dca3029acf9d1eae327fdd9715c638fa4d106a646ff79e31aba8a9880"
---
>           "EvaluatedElement": "0397b129a689b31f11a8b1bf45fa25139cd7a7ca29e2f25c8c73c50d11a1d89838adf130dd7b5ac1fffeb00e9383ebad2f"
91c91
<           "IssuedToken": "0350f953c1ec74002d3bb1582350070ce1aec577d488afa508e091f27e765eea69dd8a814455b8cdaaa5f9391d9978b320"
---
>           "IssuedToken": "022a1898b473f9eaca1ac88583e776b3ee9d45ae47dc8bafd301eeb5c78bc82935cd1b17cf6b666748aa9b20765bff2c66"
96,97c96,97
<           "BlindedElement": "0392c7f6b0bfecf05fca809fb1680e4e1c9499f9bef5168f3358031aa2ccd43566f66d926b374047b64a6f3fbc7ccfb767",
<           "Token": "f162ac7cdaf719be997bbf22f4982eddffa371fab8dcfa66f1a4f80542c3fe50d9dd39f68aa5ef9bed0ba57d4788728c"
---
>           "BlindedElement": "032f9229686646403b19c3b10d4a24e5000fd37d2edf1ef36a96154affcdfdeefcae1df012d359eb0e3ff4fdf57bdc994e",
>           "Token": "8c8ff1b2555a3f1a7d4d381f767bfa65b65714e55153fef6d1116e4b8b3dc9794481fea792e8d1df369f9213b7593a71"
99c99
<         "ClientOutput": "e9cf62d33ff968ce9bcb0515e53c14d39aeb48e6d57c240843609f8c9df062e1f49a61881351f3a1f9b70faf252829ebe07353a2e692f38dcaa18186c7e61028",
---
>         "ClientOutput": "52e1dab55d32ef0d7adc7ea24e232c56c66a418b64e6ed79c5498435c38a41496807094463ba3053d01061c0b08746708d534e6511e3c7a4f6f1a539c0e4094f",
101c101
<           "EvaluatedElement": "03bd9b1aa2b33eb0a56e761bef35 [...]

2020-11-04 23:02 UTC, claucece commented
And to note, in my machine:

```
python: aliased to /usr/local/bin/python3
sage -v                       
SageMath version 9.1, Release Date: 2020-05-20
```

2020-11-04 23:04 UTC, chris-wood commented
> let me know what I'm doing wrong here.

I don't know what's different, but that's not behavior I'm seeing.

2020-11-04 23:06 UTC, claucece commented
@armfazh, I'll use that then, and keep this PR for removing the ristretto and decaf in the tests.

2020-11-04 23:07 UTC, claucece commented
@chris-wood I'll check then what is wrong with my machine, as I ran it again, and it created new vectors.

2020-11-05 14:15 UTC, claucece commented
I'm closing this now.

2020-11-05 14:15 UTC, closed without merging