updates fields in test vectors
cfrg/draft-irtf-cfrg-voprf pull request #188
Opened 2020-11-05 03:37 UTC by armfazh

I finally get reproducible test vectors, I suspect that the cause was grouping the suites in a set versus in a list.

2020-11-05 14:15 UTC, claucece commented
Oh nice! Thank you! Can you also delete the check for ristretto or decaf on the test file?

2020-11-05 14:20 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +To prevent no information is leaked during protocol execution, all
```suggestion
To ensure no information is leaked during protocol execution, all
```

2020-11-05 14:31 UTC, chris-wood requested changes
I quite like the change, but I think it needs to be reformatted for clarity. Also, as @claucece suggests, can we remove the special case ristretto255/decaf448 changes from the test file?

2020-11-05 14:31 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +structure as the output of `Evaluate`.
```suggestion
rather than a single input. Applications can take advantage of this
functionality by invoking `GenerateProof` on batches of inputs to 
produce a combined, constant-size proof. (In the pseudocode above, 
the single inputs `blindToken` and `element` passed as one-item lists 
to `ComputeComposites`.) 
```

2020-11-05 14:31 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +The definition of `ComputeComposites` is given below. This function is
Can we refactor this function so that it doesn't have a reference to `self` internally? It's sort of awkward as-is.

2020-11-05 14:31 UTC, chris-wood commented on poc/test_oprf.sage
> +            vectors += [ vector ]
```suggestion
            vectors.append(protocol.run())
```

2020-11-05 14:32 UTC, chris-wood commented
> I suspect that the cause was grouping the suites in a set versus in a list.

Hah! That does explain it, as I only ran one ciphersuite each time I did the test (to save time).

2020-11-05 19:30 UTC, armfazh commented
> Can you also delete the check for ristretto or decaf on the test file?

which check are you referring to?

2020-11-05 19:36 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +The definition of `ComputeComposites` is given below. This function is
I think this also extends to the contextString?
```
  seedDST = "VOPRF05-seed-" || self.contextString
```

2020-11-05 23:01 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +The definition of `ComputeComposites` is given below. This function is
I followed the same pattern of using self. Ideas are welcomed.

2020-11-06 00:21 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +The definition of `ComputeComposites` is given below. This function is
Ohh, yeah. Hmm. How about we merge as-is and then I make an attempt at clarifying after?

2020-11-06 00:22 UTC, chris-wood approved these changes

2020-11-06 00:23 UTC, merged