Restructure test vectors
cfrg/draft-irtf-cfrg-voprf pull request #190
Opened 2020-11-08 18:35 UTC by chris-wood

And write them to in text format (for the spec). Sample output:

```
## OPRF(ristretto255, SHA-256)

### Base Mode

skS = 0x38ecf12e5465e4f1362d237521104338cde6717e26a25a5770da7ad85c70
4c6 

#### Test Vector 1

Input = 0x00 
Blind = 0xbe537e02b0116a48941a76d08b3af2366cc6ee4237b306d3153fc6b209
5d85e 
BlindedElement = 0xdcdfdc7560b0fb00809bbddc395eb740ec198e3a3d098c074
1a077fa20fc8126 
EvaluatedElement = 0x9e066b349ff1f2e1eb82264f9777ce63fe3aea2e429e944
9b89116fb1b85871d 
UnblindedElement = 0xe81179b0fa0b03ab4f1d4e557233f17bd05d23f158d3255
2def49a0d38ea5249 
Info = 0x736f6d655f696e666f00 
Output = 0xeae38ae2f64e3747e185c7fa058141352da46f94f231c7db6b7b4c943
5033545 

...
```

2020-11-09 15:24 UTC, dvorak42 commented
Generally seems good, though it might be useful to have some test vectors with multiple elements for the batching/ComputeComposites primitive.

2020-11-09 17:20 UTC, chris-wood commented
> Generally seems good, though it might be useful to have some test vectors with multiple elements for the batching/ComputeComposites primitive.

That's a great point! I'll add that.

2020-11-09 18:23 UTC, armfazh requested changes

2020-11-09 18:23 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +  Random Oracle, whose output length is Nh bytes long.
I think it is better to define `Nh` parameter in Section 2.

2020-11-09 18:23 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +def Unblind(token, blindedElement, eval):
4 params

2020-11-09 18:23 UTC, armfazh commented on poc/groups.sage
> +        L = int(((log(self.p, 2) + 8) / 8).n())
```suggestion
        L = int( ceil( log(self.p, 2) / 8 ) )
```

2020-11-09 18:23 UTC, armfazh commented on poc/vectors/allVectors.json
> +          "EvaluatedElement": "0x029d3a5826f781235a01e544795273e9a28b5a56e2e476a8bdf36dfc1252a7e09d",
EvaluationElement?

2020-11-09 18:23 UTC, armfazh commented on poc/test_oprf.sage
> +    with open(path + "/allVectors.txt", 'wt') as f:
Add txt file to repo?

2020-11-09 18:33 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  Random Oracle, whose output length is Nh bytes long.
There's a separate issue for that. I'll do it there.

2020-11-09 18:33 UTC, chris-wood commented on poc/groups.sage
> +        L = int(((log(self.p, 2) + 8) / 8).n())
This is unchanged, so resolving.

2020-11-09 18:33 UTC, chris-wood commented on poc/vectors/allVectors.json
> +          "EvaluatedElement": "0x029d3a5826f781235a01e544795273e9a28b5a56e2e476a8bdf36dfc1252a7e09d",
👍

2020-11-09 18:33 UTC, chris-wood commented on poc/test_oprf.sage
> +    with open(path + "/allVectors.txt", 'wt') as f:
I left it out for now, since it's only needed for the document. We can add it though.

2020-11-09 19:38 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +def Unblind(token, eval):
This should be fixed.

2020-11-09 21:16 UTC, armfazh approved these changes

2020-11-09 22:44 UTC, merged

2020-11-10 00:20 UTC, bytemare commented on draft-irtf-cfrg-voprf.md
> +  Element blindedPublicKey
Why use `blindedPublicKey` as input and output of this function, since it is not used?

2020-11-10 00:21 UTC, bytemare commented on draft-irtf-cfrg-voprf.md
> +  return blind, blindedGenerator, blindedPublicKey
Why return the `blind` when it is not used afterward?

2020-11-10 00:22 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  return blind, blindedGenerator, blindedPublicKey
This was fixed in a followup change!

2020-11-10 00:23 UTC, bytemare commented on draft-irtf-cfrg-voprf.md
> +  Element blindedPublicKey
Why use `blindedPublicKey` as input and output of this function, since it is not used?

2020-11-10 00:26 UTC, bytemare commented on draft-irtf-cfrg-voprf.md
> +  return blind, blindedGenerator, blindedPublicKey
Oh, I'm sorry about that! Missed it!