Specifies N parameters in test vectors.
cfrg/draft-irtf-cfrg-voprf pull request #212
Opened 2020-11-12 19:26 UTC by armfazh

Note that `Ne` is implementation-dependant as points could be compressed or not.

2020-11-12 23:35 UTC, chris-wood requested changes
I think these should go in the ciphersuite definition, under the group. (It's currently a lot of redundant text in the draft otherwise.)

2020-11-12 23:35 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +Ne = 32
Can we list these in the ciphersuite section, rather than the test vectors? (Also, since this text is generated automatically by Sage, we'd have to augment that code to spit them out.)

2020-11-13 02:07 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +Ne = 32
That's why I did, I modified the sage script.
Changes comming soon.

2020-11-13 22:24 UTC, chris-wood requested changes
I don't like that we now make point compression optional. Let's pick one and stick with it, please. (Also, note the formatting suggestion to include spaces around ` = ` for clarity.)

2020-11-13 22:24 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  - Serialization: Both group elements and scalars are encoded in Ne=Ns=32
```suggestion
  - Serialization: Both group elements and scalars are encoded in Ne = Ns = 32
```

2020-11-13 22:24 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  - Serialization: Both group elements and scalars are encoded in Ne=Ns=56
```suggestion
  - Serialization: Both group elements and scalars are encoded in Ne = Ns = 56
```

2020-11-13 22:24 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  - Serialization: Group elements are encoded in Ne=33 bytes if compressed
Please revert this. We should be either point compression or not, otherwise implementers may be left confused about what to use for Ne and Ns. Suggestion:

~~~
Elements are serialized as Ne = 33 byte strings using compressed point encoding for the curve {{SEC1}}.
Scalars are serialized as Ns = 32 byte strings by fully reducing the value modulo p and in big-endian order.
~~~

2020-11-13 23:05 UTC, chris-wood approved these changes
LGTM -- thanks!

2020-11-13 23:05 UTC, merged