Add clarifications about batching.
cfrg/draft-irtf-cfrg-voprf pull request #217
Opened 2020-11-23 22:59 UTC by bytemare

Closes #201.

2020-11-24 01:38 UTC, chris-wood requested changes
Thanks for the text! I think this can be simplified somewhat and merged with already existing text. Please let me know what you think of the suggestion.

2020-11-24 01:38 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +### Batching
This text is somewhat redundant with what's in the "Batching inputs" section. Would it be possible to add this paragraph to the end of that section? 

```
In particular, servers can produce a single, constant-sized proof for N 
client inputs, rather than one proof per client input. This optimization 
benefits clients and servers since it amortizes the cost of proof generation 
and bandwidth across multiple requests.
```

2020-11-24 02:06 UTC, armfazh reviewed
Some comments

2020-11-24 02:06 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +we would bring that down to N evaluations and 1 proof in 1 roundtrip.
Feel free to edit as needed.

```suggestion
benefits both the server and the client. Hence, for N blinded inputs from the
client, instead of having N roundtrips for fetching N evaluations and N proofs,
we would bring that down to a single roudtrip carrying N evaluations and 
one proof.
```

2020-11-24 02:06 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +### Batching
Does batching deserves its own section to highlight its relevance?

```suggestion
## Batching
```

2020-11-24 12:07 UTC, bytemare commented on draft-irtf-cfrg-voprf.md
> +### Batching
Do you mean dropping this (@armfazh suggestions have been included)

> ## Batching
> 
> Clients that need multiple verifiable evaluations would make as many requests
> to the server. Batching the inputs enables the server to evaluate them all
> individually and to compute a single NIZK proof for the whole set at once.
> 
> With this technique, the client sends a set of blindedElements to the server,
> and the server responds with the set of evaluatedElements and a single proof object
> (proofC and proofS).
> 
> The optimization takes place in the ComputeComposites function, and therefore
> benefits both the server and the client. Hence, for N blinded inputs from the
> client, instead of having N roundtrips for fetching N evaluations and N proofs,
> we would bring that down to a single roundtrip carrying N evaluations and 
> one proof.

and adding your paragraph to `##### Batching inputs` instead? Or merging the suggestions and adding them to `##### Batching inputs`?

2020-11-24 14:03 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +### Batching
I suggest the former! I think the proposed text (with @armfazh's suggestions) have more words than are needed.

2020-11-24 15:07 UTC, bytemare commented on draft-irtf-cfrg-voprf.md
> +### Batching
Indeed, it's much more concise. May I suggest adding the notion of the client sending the batch in a single request, though? So it's undoubtedly clear to the reader it's not about sparse elements the client sends over time.

How about this:
> In particular, servers can produce a single, constant-sized proof for N 
> client inputs sent in a single request, rather than one proof per client
> input. This optimization benefits clients and servers since it amortizes
> the cost of proof generation and bandwidth across multiple requests.

2020-11-24 15:30 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +### Batching
Looks good!

2020-11-24 18:52 UTC, armfazh approved these changes

2020-11-25 14:54 UTC, chris-wood approved these changes

2020-11-25 14:55 UTC, merged