Highlighting key generation functions.
cfrg/draft-irtf-cfrg-voprf pull request #246
Opened 2021-04-30 20:07 UTC by armfazh

This change unhides the key related operations based on primer order groups.

2021-04-30 23:02 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  compute `skS = HashToScalar(seed)` and `pkS = ScalarBaseMult(skS)`.
Why not make this the required implementation? (OPAQUE, for example, depends on the function being implemented this way.)

2021-04-30 23:02 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +### Mathematical Operations
```suggestion
```

2021-04-30 23:02 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +### Cryptographic Operations
```suggestion
```

2021-04-30 23:02 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +- HashToGroup(x): A member function of `GG` that deterministically maps
Hmm, why isn't this an API on the group? (The description specifically says this is a member function of `GG`, for example.)

2021-04-30 23:02 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +- GenerateKeyPair(): Samples at random a private key `skS`, generates
GenerateKeyPair and DeriveKeyPair seem to be the two functions here that are probably best pulled out of the POG API. What do you think?

2021-04-30 23:02 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +cryptographic purposes.
```suggestion
We also assume the two following functions for generating OPRF key pairs.
```

2021-04-30 23:44 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +- GenerateKeyPair(): Samples at random a private key `skS`, generates
I agree, so we can relocate them to a different section. (together with the hash* see other comment)

2021-04-30 23:48 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +- HashToGroup(x): A member function of `GG` that deterministically maps
it's true, it doesn't need to be part of "the crypto API"

2021-04-30 23:50 UTC, armfazh commented
ok, I'm going to refactor based on these comments.

2021-05-04 18:43 UTC, armfazh commented
I've updated the PR according to the review.

2021-05-04 20:03 UTC, chris-wood requested changes

2021-05-04 20:03 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +## Key Generation
Can we move this section up to the where the old text was? It seems more natural to follow the description of the POG.

2021-05-04 20:03 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +def GenerateKeyPair(suite):
Hmm, I think we should only write a description for DeriveKeyPair, and then just list requirements for GenerateKeyPair. Some folks may want to implement GenerateKeyPair a different way, e.g., due to FIPS reasons or something, and we don't want to prohibit that.

2021-05-04 22:52 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +def GenerateKeyPair(suite):
take a look on latest changes.

2021-05-04 23:18 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +generated as `pkS = ScalarBaseMult(skS)`.
Why does `pkS` need to be _generated_ with this function? Maybe we can just say that `pkS = ScalarBaseMult(skS)`? (The difference being that the latter specifies the relation between `skS` and `pkS`, rather than exactly how one computes `pkS` given `skS`.)

2021-05-04 23:52 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +generated as `pkS = ScalarBaseMult(skS)`.
Better now?  (feel free to edit)

```suggestion
Two functions can be used for generating a (V)OPRF key pair (`skS`, `pkS`).
The `DeriveKeyPair` function deterministically generates the private key
`skS` given a random byte string `seed` that SHOULD have at least `Ns`
bytes of length; to do that, compute `skS = GG.HashToScalar(seed)`.
The `GenerateKeyPair` function is a randomized algorithm that outputs a
key pair (`skS`, `pkS`). Both functions must guarantee that the private
key `skS` is a non-zero integer less than `p`, and the public key is
`pkS = ScalarBaseMult(skS)`.
```

2021-05-05 17:45 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +generated as `pkS = ScalarBaseMult(skS)`.
How about this slightly different variant?

```suggestion
Two functions can be used for generating a (V)OPRF key pair (`skS`, `pkS`)
with the relation `pkS = ScalarBaseMult(skS)`: `GenerateKeyPair` and 
`DeriveKeyPair`. `GenerateKeyPair` is a randomized function that outputs
a fresh key pair (`skS`, `pkS`) upon ever invocation. `DeriveKeyPair` is a 
deterministic  function that generates private key `skS` from a random byte 
string `seed` that  SHOULD have at least `Ns` bytes of entropy, and then 
computes `pkS = ScalarBaseMult(skS)`. Both functions must guarantee that 
the private key `skS` is a non-zero integer less than `p`.
```

2021-05-05 18:17 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +generated as `pkS = ScalarBaseMult(skS)`.
so much better,

2021-05-06 00:58 UTC, chris-wood approved these changes

2021-05-06 00:58 UTC, merged