Major refactor to focus on three protocol variants: OPRF, VOPRF, and POPRF
cfrg/draft-irtf-cfrg-voprf pull request #304
Opened 2022-01-07 00:32 UTC by chris-wood

This refactor is predicated on the observation that 2HashDH and 3HashSDHI are equivalent for the non-verifiable case, and that public input is only really relevant for the verifiable case. The end result is three protocol variants in the spec: a base OPRF mode that is not variable, a 2HashDH verifiable mode without public input, and a 3HashDH-SDHI variant that is verifiable with public input. 

I think this is a good compromise given all the considerations involved -- threshold VOPRF, huzzah! -- and in the end yields a more understandable document. I also think the new structure should be easier to follow. 

Note: test vectors have not yet been updated. I will do that in a followup series of commits once this gets some approvals.

cc @kevinlewi, @bytemare, @hugokraw, @tomrist

2022-01-07 18:31 UTC, bytemare requested changes

2022-01-07 18:31 UTC, bytemare commented on draft-irtf-cfrg-voprf.md
>  the server commits to the key before the actual protocol execution takes
Would it be clearer precising that "commitment" implies that the client has the server's public key before protocol execution?

2022-01-07 18:33 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  output = Finalize(input, blind, evaluatedElement, blindedElement, proof)
I omitted these from all functions here and assumed they're implicit, since they're provided during context creation.

2022-01-07 18:33 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> -  Element pkS
Pulled from the context, and described in a comment at the top of the {{online}} section.

2022-01-07 18:33 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
>  the server commits to the key before the actual protocol execution takes
That's already the case. The client receives passes the public key in the context creation (offline) phase.

2022-01-07 18:38 UTC, bytemare approved these changes

2022-01-10 08:22 UTC, armfazh requested changes
some small comments

2022-01-10 14:09 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  return CT_EQUAL(expectedC, c)
```suggestion
  return expectedC == c
```

2022-01-10 14:10 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  return CT_EQUAL(expectedC, c)
proof.c is a byte string, whereas expectedC is a scalar. I'll just make this `==`.

2022-01-10 14:11 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +used both on generation and verification of the proof.
```suggestion
used both for verification of the proof.
```

2022-01-10 14:11 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +used both on generation and verification of the proof.
```suggestion
The definition of `ComputeComposites` is given below.
```

2022-01-10 14:13 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +the `Evaluate` function is the same key as it used to produce their public key.
```suggestion
the `Evaluate` function is the same private key corresponding to the server's public key.
```

2022-01-10 14:18 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +    "VOPRF08-" || I2OSP(modeVOPRF, 1) || I2OSP(suiteID, 2)
The purpose of these setup functions is to create the context string and then the context used for the online portion of the protocol, so I think it's better as-is. But your comment wasn't really clear to me, so maybe I'm missing your point?

2022-01-10 14:19 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +Errors: DeserializeError, InverseError
Yep, copy pasta. Thanks.

2022-01-10 14:19 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +Errors: DeserializeError, InverseError
```suggestion
Errors: DeserializeError
```

2022-01-10 14:21 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +at once whilst only constructing one NIZK proof object. This is enabled using
```suggestion
at once whilst only constructing one proof object. This is enabled using
```

2022-01-10 14:22 UTC, chris-wood commented
@armfazh suggestions applied and comments resolved. Please have another look.

2022-01-10 16:25 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +    "VOPRF08-" || I2OSP(modeVOPRF, 1) || I2OSP(suiteID, 2)
I don't think that's an improvement in clarity. In any case, it's editorial, so I think we can resolve this.

2022-01-10 21:20 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +at once whilst only constructing one NIZK proof object. This is enabled using
not resolved yet

2022-01-10 21:21 UTC, armfazh approved these changes

2022-01-10 22:47 UTC, bytemare commented on draft-irtf-cfrg-voprf.md
> +    "VOPRF08-" || I2OSP(modeVOPRF, 1) || I2OSP(suiteID, 2)
I agree with @armfazh, and to me, it reads more clearly :)

2022-01-10 22:57 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +    "VOPRF08-" || I2OSP(modeVOPRF, 1) || I2OSP(suiteID, 2)
Fair enough -- done!

2022-01-11 02:24 UTC, bytemare commented on draft-irtf-cfrg-voprf.md
> +  proof = GenerateProof(skS, G, pkS, R, Z)
R and Z and inverted compared to the POPRF mode. Is that intentional?

2022-01-11 02:55 UTC, bytemare requested changes
There seems to be an error for the client and server in VOPRF when calling generate and verify functions.
The `C` argument in GenerateProof should be evaluated elements, and `D` argument blinded. Same for verification.
R is the blinded element, Z is the evaluation.

2022-01-11 02:55 UTC, bytemare commented on draft-irtf-cfrg-voprf.md
> +  proof = GenerateProof(skS, G, pkS, R, Z)
```suggestion
  proof = GenerateProof(skS, G, pkS, Z, R)
```

2022-01-11 02:55 UTC, bytemare commented on draft-irtf-cfrg-voprf.md
> +  if VerifyProof(G, pkS, R, Z, proof) == false:
```suggestion
  if VerifyProof(G, pkS, Z, R, proof) == false:
```

2022-01-11 02:55 UTC, bytemare commented on draft-irtf-cfrg-voprf.md
> +  proof = GenerateProof(skS, G, pkS, R, Z)
```suggestion
  proof = GenerateProof(skS, G, pkS, R, Z)
```
```suggestion
  proof = GenerateProof(skS, G, pkS, Z, R)
```

2022-01-11 02:55 UTC, bytemare commented on poc/oprf.sage
> +        if not self.verify_proof(G, self.pkS, [R], [Z], proof):
```suggestion
        if not self.verify_proof(G, self.pkS, [Z], [R], proof):
```

2022-01-11 02:55 UTC, bytemare commented on poc/oprf.sage
> +        if not self.verify_proof(G, self.pkS, Rs, Zs, proof):
```suggestion
        if not self.verify_proof(G, self.pkS, Zs, Rs, proof):
```

2022-01-11 02:55 UTC, bytemare commented on poc/oprf.sage
> +        proof, r = self.generate_proof(self.skS, self.suite.group.generator(), self.pkS, [R], [Z])
```suggestion
        proof, r = self.generate_proof(self.skS, self.suite.group.generator(), self.pkS, [Z], [R])
```

2022-01-11 02:55 UTC, bytemare commented on poc/oprf.sage
> +        proof, r = self.generate_proof(self.skS, self.suite.group.generator(), self.pkS, Rs, Zs)
```suggestion
        proof, r = self.generate_proof(self.skS, self.suite.group.generator(), self.pkS, Zs, Rs)
```

2022-01-11 14:56 UTC, bytemare commented
@caw We could piggyback #291 in this PR

2022-01-11 14:57 UTC, chris-wood commented
@bytemare I figured we'd leave that out for now, since this is _primarily_ a refactoring.

2022-01-11 14:58 UTC, chris-wood commented on poc/oprf.sage
> +        compositeDST = _as_bytes("Composite")
Yep, good idea!

2022-01-13 00:57 UTC, chris-wood commented
Ready for review. @alxdavids, please let me know if you will or will not have time to review this.

2022-01-13 01:13 UTC, kevinlewi approved these changes

2022-01-13 13:43 UTC, alxdavids commented
@chris-wood I will review it, but I won't be able to get it done until the start of next week. Does this need to move on a quicker timeframe?

2022-01-15 20:09 UTC, bytemare approved these changes

2022-01-15 20:09 UTC, bytemare commented
Forgot to confirm that vectors are ok!

2022-01-17 14:16 UTC, merged