DeriveKeyPair and serialization improvements
cfrg/draft-irtf-cfrg-voprf pull request #308
Opened 2022-01-13 16:53 UTC by chris-wood

Based on #304. DO NOT MERGE.

[Rendered version of this PR.](https://cfrg.github.io/draft-irtf-cfrg-voprf/caw/dkp-and-serialize/draft-irtf-cfrg-voprf.html)

2022-01-15 16:54 UTC, bytemare requested changes

2022-01-15 16:54 UTC, bytemare commented on draft-irtf-cfrg-voprf.md
> +Upon receipt, servers processs `blindedElement` using the `Evaluate` function described
```suggestion
Upon receipt, servers process `blindedElement` using the `Evaluate` function described
```

2022-01-17 21:40 UTC, bytemare commented on draft-irtf-cfrg-voprf.md
> +    skS = GG.HashToScalar(deriveInput || I2OSP(counter, 1),
`counter` is bound between 0 and 255, so technically an unsigned 8-bit integer, a byte. Does it make sense to explicitly I2OSP it to one byte?

2022-01-17 22:19 UTC, bytemare requested changes

2022-01-17 22:19 UTC, bytemare commented on draft-irtf-cfrg-voprf.md
>  ## Error Considerations
This part of the section

> Some OPRF variants specified in this document have fallible operations. For example, `Finalize`
and `Evaluate` can fail if any element received from the peer fails deserialization.

might need to be updated, since Finalize doesn't deserialize anymore

2022-01-17 22:47 UTC, armfazh requested changes

2022-01-17 22:47 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +are opaque byte strings of arbitrary length no larger than 2^13 octets.
we can leverage the TLS syntax notation to express these types.

2022-01-17 22:47 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +    Client(pkS)            <---- pkS ------                 Server(skS)
not really agree with this arrow. it was implicit that the client obtained server's key by any method, not precisely server sending its key to client.
e.g. Client could get key by pre-installation.

2022-01-17 22:47 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +    Client(pkS)            <---- pkS ------                 Server(skS)
otoh, does the server require to use a certificate that proves ownership of the pair of keys? (*I was told the protocol is PKI-free)

2022-01-17 22:47 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
>  to as `suiteID`; see {{ciphersuites}} for the registry of initial values.
```suggestion
to as `ID`; see {{ciphersuites}} for the registry of initial values.
```

2022-01-17 22:47 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +using the following function, which accepts a randmly generated seed of length
```suggestion
using the following function, which accepts a randomly generated seed of length
```

2022-01-17 22:47 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
>    N = blind^(-1) * Z
Z is not defined

2022-01-17 22:47 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
>  Errors: DeserializeError, VerifyError
```suggestion
Errors: VerifyError
```

2022-01-17 22:47 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +  if VerifyProof(G, U, evaluatedElement, blindedElement, proof) == false:
as U is a multiple of G, 
so blinded is a multiple of evaluated element, (double check)

2022-01-17 22:47 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +and instead expose interfaces that operate in terms of wire format messages.
this means that applications can define its own serialization for objects? or applications must comply with the serialization recommended in this doc? not clear to me.

2022-01-17 22:50 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +are opaque byte strings of arbitrary length no larger than 2^13 octets.
I don't think that's appropriate. These are just byte strings, not length prefixed byte strings or anything.

2022-01-17 22:51 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +    Client(pkS)            <---- pkS ------                 Server(skS)
This simply means the client gets the public key from the server, somehow. That can be preinstallation.

2022-01-17 22:53 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +and instead expose interfaces that operate in terms of wire format messages.
It means that how applications choose to expose the external API is up to them. Does that clarify?

2022-01-17 22:56 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +and instead expose interfaces that operate in terms of wire format messages.
last question, does the wire format is no more a MUST in order to be compliant with this draft?

2022-01-17 22:57 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +  if VerifyProof(G, U, evaluatedElement, blindedElement, proof) == false:
are you saying this is incorrect as is?

2022-01-17 22:58 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +and instead expose interfaces that operate in terms of wire format messages.
Applications that use the OPRF define how to send protocol messages. They can use the wire formats (serialized forms) defined here or something else.

2022-01-17 23:08 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +  if VerifyProof(G, U, evaluatedElement, blindedElement, proof) == false:
I double-checked, it's fine because of the inverse of `t`

2022-01-17 23:19 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +    skS = GG.HashToScalar(deriveInput || I2OSP(counter, 1),
Yeah, I think so. We don't say the type of counter is an unsigned byte, so this makes it explicit.

2022-01-17 23:45 UTC, chris-wood commented
Thanks for the reviews! I'll update based on the latest comments and then update test vectors, too. (This will change how keys are derived, so the vectors will change.)

2022-01-18 00:33 UTC, chris-wood commented
This branch is incredibly screwed up. Blowing it away and starting anew.

2022-01-18 00:33 UTC, closed without merging