Include more details in DLEQ proof section.
cfrg/draft-irtf-cfrg-voprf pull request #336
Opened 2022-04-28 23:46 UTC by armfazh

It addresses the following items from [review](https://mailarchive.ietf.org/arch/msg/crypto-panel/QXC3drh1hs-XGkXyjwyCj_pFNNI/)

>   2.  2.2 on page 10 says "... proving that the discrete log of two values is identical in zero knowledge" without ever defining discrete log and zero knowledge proofs. The authors say that their construction is built on Chaum-Pedersen proof, but no further details are provided.
>   4.  2.2.1 on page 11 ends the description of GenerateProof without ever describing why the output of the function [c , s] is a discrete log equivalence proof and why is it zero knowledge.
>   5.  2.1 on page 8 starts talking about groups and then suddenly mentions finite fields without explaining what they are. It becomes clear reading further down that the authors need them for scalars. It would have been less confusing if they simply used the set of integers {0, 1, ..., p-1}.

2022-04-29 22:43 UTC, chris-wood requested changes
Requesting some additional details, and removing of some seemingly unnecessary text.

2022-04-29 22:43 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +B to the base A.
```suggestion
B with respect to the base A.
```

2022-04-29 22:43 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +the proof is zero-knowledge.
```suggestion
nothing beyond the truthiness of the statement claimed by the prover,
the proof is zero-knowledge.
```

2022-04-29 22:43 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +This section describes a noninteractive zero-knowledge proof for the discrete
```suggestion
This section describes a noninteractive zero-knowledge proof for discrete
```

2022-04-29 22:43 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +logarithm equivalence (DLEQ), that is, proving that two pairs of group elements
```suggestion
logarithm equivalence (DLEQ). A DLEQ proof demonstrates that two pairs of group elements
```

2022-04-29 22:43 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +have the same discrete logarithm, but without revealing the discrete logarithm.
```suggestion
have the same discrete logarithm without revealing the discrete logarithm.
```

2022-04-29 22:43 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +private key while the client learns nothing about its value.
```suggestion
```
I think we can note this where the proof is actually used.

2022-04-29 22:43 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +The proof presented below is built on the Chaum-Pedersen's {{ChaumPedersen}}
```suggestion
The specific DLEQ proof construcgtion presented below is built on the Chaum-Pedersen {{ChaumPedersen}}
```

2022-04-29 22:43 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +can use batching techniques shown by Henry {{Hen14}}.
Can we point to the specific section of this thesis where the batching technique is used?

2022-04-29 23:43 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +the proof is zero-knowledge.
it looks that the definition of `truthiness` is not accurate [Webster](https://www.merriam-webster.com/dictionary/truthiness)
[`veracity`](https://www.merriam-webster.com/dictionary/veracity) is more formal

2022-04-30 01:03 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +can use batching techniques shown by Henry {{Hen14}}.
done

2022-04-30 11:55 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +the proof is zero-knowledge.
While veracity fits the mold, I think truthiness is more understandable to most people, so I would prefer to use that.

2022-05-02 21:44 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +nothing beyond the truthiness of the statement claimed by the prover,
```suggestion
nothing beyond the validity of the statement claimed by the prover,
```

I wonder if this is even _more_ clear?

2022-05-02 22:47 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +nothing beyond the truthiness of the statement claimed by the prover,
It sounds clearer, but it according to [this](https://web.stanford.edu/~bobonich/terms.concepts/valid.sound.html) is not correct.

> Validity and invalidity apply only to arguments, not statements.

This workaround is a safe option:

`If the verifier learns nothing other than the statement claimed by the prover is true, the proof is zero-knowledge.`

2022-05-03 09:17 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +nothing beyond the truthiness of the statement claimed by the prover,
That works, but here's a slight rephrasing: `If the verifier learns nothing other than whether the statement claimed by the prover is true or false, the proof is zero-knowledge.`

2022-05-03 17:47 UTC, armfazh commented on draft-irtf-cfrg-voprf.md
> +nothing beyond the truthiness of the statement claimed by the prover,
applied that suggestion

2022-05-07 12:44 UTC, chris-wood approved these changes

2022-05-07 12:44 UTC, chris-wood commented on draft-irtf-cfrg-voprf.md
> +by Jarecki, et al. {{JKK14}} and use a product test batching technique
```suggestion
by Jarecki, et al. {{JKK14}} and uses the product test batching technique
```

2022-05-07 12:44 UTC, merged